/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.pinkienort.jsoncomposer.sample

import com.pinkienort.jsoncomposer.Json

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println("main")
}


